DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE likes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  answer_id  INTEGER REFERENCES answers(id) ON DELETE CASCADE,
  timestamp DATE NOT NULL DEFAULT CURRENT_DATE
);